# Generated by Django 3.2 on 2021-05-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0004_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
