# Generated by Django 3.2 on 2021-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0007_mascota_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='dueno',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
